matrix:
  - name: Markdown
    sources:
      - "**/*.md"
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
