name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: prompt-name
    attributes:
      label: Prompt Name
      description: Which prompt is experiencing the issue?
      placeholder: e.g., Code Review Assistant
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does this prompt belong to?
      options:
        - Development
        - Writing
        - Business
        - Analysis
        - Creative
        - Education
        - Productivity
        - Templates
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue you encountered
      placeholder: Tell us what went wrong!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Use prompt with '....'
        3. See error
    validations:
      required: true
  - type: dropdown
    id: ai-model
    attributes:
      label: AI Model Used
      description: Which AI model were you using?
      options:
        - ChatGPT (GPT-4)
        - ChatGPT (GPT-3.5)
        - Claude (Anthropic)
        - Gemini (Google)
        - Other
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
