name: Feature Request
description: Suggest a new prompt or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or improvement!
  - type: dropdown
    id: request-type
    attributes:
      label: Request Type
      description: What type of feature are you requesting?
      options:
        - New Prompt
        - Prompt Enhancement
        - Documentation Improvement
        - Template Addition
        - Example Addition
        - Other
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category would this fit into?
      options:
        - Development
        - Writing
        - Business
        - Analysis
        - Creative
        - Education
        - Productivity
        - Templates
        - New Category
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe your feature request in detail
      placeholder: What would you like to see added or improved?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case or problem this would solve
      placeholder: How would this be used? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas for how to implement this, please share them
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my work
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to contribute code for this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to provide examples/testing
