name: Quality Assurance

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Markdown Lint
    steps:
      - uses: actions/checkout@v5

      - name: Lint Markdown files
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: "**/*.md"
          ignore: "node_modules"
  template-compliance:
    runs-on: ubuntu-latest
    name: Template Compliance Check
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Check prompt template compliance
        run: |
          python scripts/check-template-compliance.py
        continue-on-error: true

  internal-links:
    runs-on: ubuntu-latest
    name: Internal File Link Check
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Check internal file links
        run: |
          python scripts/check-internal-links.py --verbose
